### ISSUE TITLE
Retrieving Fiscal Years available is filtered

### ISSUE THREAD

**Issue by msheldont4e** [Tools4everBV/HelloID-Conn-Prov-Source-Skyward-Qmlativ-Employees#2]
https://github.com/Tools4everBV/HelloID-Conn-Prov-Source-Skyward-Qmlativ-Employees/blob/1befa9552bce6e952d5c22ac169aa38dabd5565f/persons.ps1#L159

Currently when it returns the fiscal year table it is filtered by the configuration fiscal id. We should ignore this.

**Comment by rschouten97** [comment]
@msheldont4e I don't quite know this connector and system. But it seems this still applies, correct?
Can you provide an example of how the solution so we can implement this/update this on Git?

**Comment by rschouten97** [comment]
Closed due to inactivity.
If this is still an active issue, please let us know and we will re-open this.
